version: '3.5'
services:
  nginx: 
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - stackoverflow-light-net
    ports:
      - 80:80

networks:
  stackoverflow-light-net:
    external: true
